{
 "title": "MIF-DP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodes",
    "label": "nodes",
    "query": {
     "query": "label_values(gpu_gfx_activity,hostname)"
    }
   },
   {
    "name": "prefill",
    "label": "prefill",
    "query": {
     "query": "label_values(llm_time_to_first_token_seconds_bucket{role=\"prefill\"},job)"
    }
   },
   {
    "name": "decode",
    "label": "decode",
    "query": {
     "query": "label_values(llm_time_to_first_token_seconds_bucket{role=\"decode\"},job)"
    }
   },
   {
    "name": "heimdall",
    "label": "heimdall",
    "query": {
     "query": "label_values(inference_extension_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_gfx_activity{hostname=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(gpu_id) (gpu_gfx_activity{hostname=\"$nodes\"})",
     "legendFormat": "{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Utilzation $nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 10 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(gpu_id) (gpu_gfx_activity{hostname=\"$nodes\"})",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 10 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(gpu_id) (gpu_used_vram{hostname=\"$nodes\"}) / (sum by(gpu_id) (gpu_total_vram{hostname=\"$nodes\"}))",
     "legendFormat": "{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Junction Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_junction_temperature{hostname=\"$nodes\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "Heimdall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Ready Pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inference_pool_ready_pods{job=~\"$heimdall\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Inference RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "rate(inference_objective_request_total{job=~\"$heimdall\"}[$__rate_interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(inference_objective_request_error_total{job=~\"$heimdall\"}[$__rate_interval])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Heimdall E2EL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(inference_extension_scheduler_e2e_duration_seconds_bucket{job=~\"$heimdall\"}[$__rate_interval])))",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, pod) (rate(inference_extension_scheduler_e2e_duration_seconds_bucket{job=~\"$heimdall\"}[$__rate_interval])))",
     "legendFormat": "P75 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(inference_extension_scheduler_e2e_duration_seconds_bucket{job=~\"$heimdall\"}[$__rate_interval])))",
     "legendFormat": "P95 {{pod}}"
    }
   ]
  },
  {
   "title": "Heimdall KVCache hit/req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(kvcache_index_lookup_hits_total{job=~\"$heimdall\"}[$__rate_interval]))/sum(rate(kvcache_index_lookup_requests_total{job=~\"$heimdall\"}[$__rate_interval]))",
     "legendFormat": "hit/req"
    }
   ]
  },
  { "title": "InferenceService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Prefill TTFT per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Prefill TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode TTFT per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill ITL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, pod) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{pod}}"
    }
   ]
  },
  {
   "title": "Prefill ITL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode ITL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode ITL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill E2EL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, pod) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{pod}}"
    }
   ]
  },
  {
   "title": "Prefill E2EL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode E2EL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode E2EL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill ISL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(llm_request_prompt_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, pod) (rate(llm_request_prompt_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(llm_request_prompt_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{pod}}"
    }
   ]
  },
  {
   "title": "Prefill ISL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_prompt_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_prompt_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_prompt_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode ISL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(llm_request_prompt_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, pod) (rate(llm_request_prompt_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(llm_request_prompt_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95 {{pod}}"
    }
   ]
  },
  {
   "title": "Decode ISL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_prompt_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_prompt_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_prompt_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill OSL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(llm_request_generation_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, pod) (rate(llm_request_generation_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(llm_request_generation_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{pod}}"
    }
   ]
  },
  {
   "title": "Prefill OSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_generation_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_generation_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_generation_tokens_bucket{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode OSL per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(llm_request_generation_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, pod) (rate(llm_request_generation_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(llm_request_generation_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95 {{pod}}"
    }
   ]
  },
  {
   "title": "Decode OSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_generation_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_generation_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_generation_tokens_bucket{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill KVCache Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "llm_kv_cache_usage_perc{job=~\"$prefill\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefill KVCache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(llm_kv_cache_usage_perc{job=~\"$prefill\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decode KVCache Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "llm_kv_cache_usage_perc{job=~\"$decode\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Decode KVCache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(llm_kv_cache_usage_perc{job=~\"$decode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefill waiting queue per DP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "llm_num_requests_waiting{job=~\"$prefill\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefill waiting queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "targets": [
    {
     "expr": "avg(llm_num_requests_waiting{job=~\"$prefill\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decode waiting queue per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "llm_num_requests_waiting{job=~\"$decode\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Decode waiting queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "targets": [
    {
     "expr": "avg(llm_num_requests_waiting{job=~\"$decode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefill prefix hit rate per DP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(llm_prefix_cache_hits_total{job=~\"$prefill\"}[$__rate_interval])) * 100) / (sum by(instance) (rate(llm_prefix_cache_queries_total{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Decode prefix hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(llm_prefix_cache_hits_total{job=~\"$prefill\"}[$__rate_interval])) * 100) / (sum(rate(llm_prefix_cache_queries_total{job=~\"$prefill\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Decode prefix hit rate per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(llm_prefix_cache_hits_total{job=~\"$decode\"}[$__rate_interval])) * 100) / (sum by(instance) (rate(llm_prefix_cache_queries_total{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Decode prefix hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(llm_prefix_cache_hits_total{job=~\"$decode\"}[$__rate_interval])) * 100) / (sum(rate(llm_prefix_cache_queries_total{job=~\"$decode\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prefill running queue per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "llm_num_requests_running{job=\"$prefill\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Decode runnung queue per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "llm_num_requests_running{job=\"$decode\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}