{
 "title": "MIF",
 "tags": [
  "mif",
  "gpu"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "amd_nodes",
    "label": "amd_nodes",
    "query": {
     "query": "label_values(gpu_gfx_activity,hostname)"
    }
   },
   {
    "name": "nvidia_nodes",
    "label": "nvidia_nodes",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL,Hostname)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(inference_extension_info,namespace)"
    }
   },
   {
    "name": "inference_pool",
    "label": "inference_pool",
    "query": {
     "query": "label_values(inference_extension_info{namespace=~\"$namespace\"},pool)"
    }
   },
   {
    "name": "inference_service",
    "label": "inference_service",
    "query": {
     "query": "label_values(llm_time_to_first_token_seconds_created{pool=~\"$inference_pool\", namespace=~\"$namespace\"},inference_service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_gfx_activity{hostname=~\"$amd_nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AMD GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "repeat": "amd_nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(gpu_id) (gpu_gfx_activity{hostname=\"$amd_nodes\"})",
     "legendFormat": "{{gpu_id}}"
    }
   ]
  },
  {
   "title": "$amd_nodes GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 10 },
   "repeat": "amd_nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(gpu_id) (gpu_gfx_activity{hostname=\"$amd_nodes\"})",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 10 },
   "repeat": "amd_nodes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(gpu_id) (gpu_used_vram{hostname=\"$amd_nodes\"}) / (sum by(gpu_id) (gpu_total_vram{hostname=\"$amd_nodes\"}))",
     "legendFormat": "{{gpu_id}}"
    }
   ]
  },
  {
   "title": "$amd_nodes GPU Junction Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "repeat": "amd_nodes",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_junction_temperature{hostname=\"$amd_nodes\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "NVIDIA GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 18 },
   "repeat": "nvidia_nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(gpu) (DCGM_FI_DEV_GPU_UTIL{Hostname=\"$nvidia_nodes\"})",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "$nvidia_nodes GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 18 },
   "repeat": "nvidia_nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=\"$nvidia_nodes\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 18 },
   "repeat": "nvidia_nodes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=\"$nvidia_nodes\"}\n  / on(gpu) ( \n    DCGM_FI_DEV_FB_USED{Hostname=\"$nvidia_nodes\"}\n    + on(gpu)\n      DCGM_FI_DEV_FB_FREE{Hostname=\"$nvidia_nodes\"}\n    )",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "$nvidia_nodes GPU Junction Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 18 },
   "repeat": "nvidia_nodes",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=\"$nvidia_nodes\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Heimdall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Ready Pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, pool) (inference_pool_ready_pods{namespace=~\"$namespace\", pool=~\"$inference_pool\"})",
     "legendFormat": "{{namespace}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Inference RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "sum by(namespace, pool) (rate(inference_objective_request_total{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Heimdall E2EL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(namespace, pool, le) (rate(inference_extension_scheduler_e2e_duration_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P50 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(namespace, pool, le) (rate(inference_extension_scheduler_e2e_duration_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P75 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, pool, le) (rate(inference_extension_scheduler_e2e_duration_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P95 {{namespace}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Heimdall KVCache hit/req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "sum by(namespace, pool) (rate(kvcache_index_lookup_hits_total{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])) / (sum by(namespace, pool) (rate(kvcache_index_lookup_requests_total{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Heimdall TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(namespace, pool, le) (rate(inference_objective_request_ttft_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P50 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(namespace, pool, le) (rate(inference_objective_request_ttft_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P75 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, pool, le) (rate(inference_objective_request_ttft_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P95 {{namespace}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Heimdall NTPOT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(namespace, pool, le) (rate(inference_objective_normalized_time_per_output_token_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P50 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(namespace, pool, le) (rate(inference_objective_normalized_time_per_output_token_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P75 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, pool, le) (rate(inference_objective_normalized_time_per_output_token_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P95 {{namespace}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Heimdall TPOT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(namespace, pool, le) (rate(inference_objective_request_tpot_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P50 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(namespace, pool, le) (rate(inference_objective_request_tpot_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P75 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, pool, le) (rate(inference_objective_request_tpot_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P95 {{namespace}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Heimdall ITL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(namespace, pool, le) (rate(inference_objective_request_itl_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P50 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(namespace, pool, le) (rate(inference_objective_request_itl_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P75 {{namespace}}/{{pool}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, pool, le) (rate(inference_objective_request_itl_seconds_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\"}[$__rate_interval])))",
     "legendFormat": "P95 {{namespace}}/{{pool}}"
    }
   ]
  },
  { "title": "InferenceService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Prefill TTFT per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Prefill TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode TTFT per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_time_to_first_token_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill ITL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Prefill ITL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode ITL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode ITL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_inter_token_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill E2EL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Prefill E2EL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode E2EL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode E2EL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_e2e_request_latency_seconds_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill ISL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Prefill ISL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode ISL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode ISL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_prompt_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill OSL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Prefill OSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Decode OSL per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75 {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95 {{instance}}"
    }
   ]
  },
  {
   "title": "Decode OSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_request_generation_tokens_bucket{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Prefill KVCache Usage per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "llm_kv_cache_usage_perc{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prefill KVCache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(llm_kv_cache_usage_perc{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Decode KVCache Usage per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "llm_kv_cache_usage_perc{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Decode KVCache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(llm_kv_cache_usage_perc{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Prefill waiting queue per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "llm_num_requests_waiting{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prefill waiting queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 91 },
   "targets": [
    {
     "expr": "avg(llm_num_requests_waiting{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=\"prefill\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Decode waiting queue per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "llm_num_requests_waiting{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Decode waiting queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 91 },
   "targets": [
    {
     "expr": "avg(llm_num_requests_waiting{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Prefill prefix hit rate per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(llm_prefix_cache_hits_total{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=\"prefill\"}[$__rate_interval]) * 100)) / (sum by(instance) (rate(llm_prefix_cache_queries_total{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prefill prefix hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(llm_prefix_cache_hits_total{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=\"prefill\"}[$__rate_interval]) * 100)) / (sum(rate(llm_prefix_cache_queries_total{namespace=~\"$namespace\", pool=~\"$inference_pool\", inference_service=~\"$inference_service\", role=\"prefill\"}[$__rate_interval])))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Decode prefix hit rate per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(llm_prefix_cache_hits_total{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])) * 100) / (sum by(instance) (rate(llm_prefix_cache_queries_total{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Decode prefix hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(llm_prefix_cache_hits_total{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])) * 100) / (sum(rate(llm_prefix_cache_queries_total{namespace=~\"$namespace\",pool=~\"$inference_pool\",inference_service=~\"$inference_service\",role=~\"decode|\"}[$__rate_interval])))",
     "legendFormat": "Avg"
    }
   ]
  }
 ]
}