apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: vllm-v0.15.1-deepseek-ai-deepseek-r1-nvidia-h200-dp16-moe-ep16
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.preset.labels" . | nindent 4 }}
    mif.moreh.io/model.org: deepseek-ai
    mif.moreh.io/model.name: deepseek-r1
    mif.moreh.io/role: e2e
    mif.moreh.io/accelerator.vendor: nvidia
    mif.moreh.io/accelerator.model: h200
    mif.moreh.io/parallelism: "dp16-moe-ep16"
spec:
  framework: vllm
  model:
    name: deepseek-ai/DeepSeek-R1
  parallelism:
    data: 16
    dataLocal: 8
    expert: true
  workerTemplate:
    spec:
      containers:
        - name: main
          image: vllm/vllm-openai:v0.15.1
          env:
            - name: VLLM_USE_DEEP_GEMM
              value: "1"
            - name: VLLM_ALL2ALL_BACKEND
              value: deepep_low_latency
            - name: ISVC_EXTRA_ARGS
              value: >-
                --trust-remote-code
                --max-model-len 65536
                --max-num-seqs 256
                --max-num-batched-tokens 57344
                --gpu-memory-utilization 0.9
                --reasoning-parser deepseek_r1
                --disable-uvicorn-access-log
                --no-enable-log-requests
          resources:
            requests:
              nvidia.com/gpu: "8"
            limits:
              nvidia.com/gpu: "8"
      nodeSelector:
        moai.moreh.io/accelerator.vendor: nvidia
        moai.moreh.io/accelerator.model: h200
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
