apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: vllm-v0.15.1-nvidia-nvidia-nemotron-3-super-120b-a12b-bf16-nvidia-h200-sxm-tp2-moe-tp2
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.preset.labels" . | nindent 4 }}
    mif.moreh.io/model.org: nvidia
    mif.moreh.io/model.name: nvidia-nemotron-3-super-120b-a12b-bf16
    mif.moreh.io/role: e2e
    mif.moreh.io/accelerator.vendor: nvidia
    mif.moreh.io/accelerator.model: h200-sxm
    mif.moreh.io/parallelism: "tp2-moe-tp2"
spec:
  framework: vllm
  model:
    name: nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16
  parallelism:
    tensor: 2
  template:
    spec:
      containers:
        - name: main
          image: vllm/vllm-openai:v0.15.1
          env:
            - name: ISVC_USE_KV_EVENTS
              value: "true"
            - name: ISVC_EXTRA_ARGS
              value: >-
                --trust-remote-code
                --max-model-len 131072
                --max-num-seqs 128
                --gpu-memory-utilization 0.90
                --kv-cache-dtype fp8
                --disable-uvicorn-access-log
                --no-enable-log-requests
          resources:
            requests:
              nvidia.com/gpu: "2"
            limits:
              nvidia.com/gpu: "2"
      nodeSelector:
        moai.moreh.io/accelerator.vendor: nvidia
        moai.moreh.io/accelerator.model: h200-sxm
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
