apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: vllm-v0.19.0-qwen-qwen3.5-122b-a10b-nvidia-h200-sxm-dp4-moe-ep4
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.preset.labels" . | nindent 4 }}
    mif.moreh.io/model.org: qwen
    mif.moreh.io/model.name: qwen3.5-122b-a10b
    mif.moreh.io/role: e2e
    mif.moreh.io/accelerator.vendor: nvidia
    mif.moreh.io/accelerator.model: h200-sxm
    mif.moreh.io/parallelism: "dp4-moe-ep4"
spec:
  framework: vllm
  model:
    name: Qwen/Qwen3.5-122B-A10B
  parallelism:
    data: 4
    expert: true
  workerTemplate:
    spec:
      containers:
        - name: main
          image: vllm/vllm-openai:v0.19.0
          env:
            - name: VLLM_USE_DEEP_GEMM
              value: "0"
            - name: ISVC_EXTRA_ARGS
              value: >-
                --trust-remote-code
                --max-model-len -1
                --gpu-memory-utilization 0.90
                --language-model-only
                --reasoning-parser qwen3
                --tool-call-parser qwen3_coder
                --enable-auto-tool-choice
                --enable-prefix-caching
                --disable-uvicorn-access-log
                --no-enable-log-requests
          resources:
            requests:
              nvidia.com/gpu: "4"
            limits:
              nvidia.com/gpu: "4"
      nodeSelector:
        moai.moreh.io/accelerator.vendor: nvidia
        moai.moreh.io/accelerator.model: h200-sxm
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
