# Change InferenceServiceTemplate to Helm template
# 1. Add `{{- include "preset.labels" . | nindent 4 }}` under .metadata.labels
# 2. Escape Go/template syntax `{{` and `}}`
# 3. --from <file|dir>
# 4. --to <file|dir>
# 5. If `--to <dir>` is given, output files are named as `<original_name>.helm.yaml`

# Generated by gemini

import argparse
import os
import re
import sys


def convert_file(input_path, output_path):
    with open(input_path, "r") as f:
        content = f.read()

    # 1. Escape Go/template syntax
    def escape_match(match):
        if match.group(0) == "{{":
            return '{{ "{{" }}'
        return '{{ "}}" }}'

    content = re.sub(r"{{|}}", escape_match, content)

    # 2. Add .metadata.labels
    lines = content.splitlines()
    new_lines = []

    metadata_regex = re.compile(r"^metadata:\s*$")
    labels_regex = re.compile(r"^(\s*)labels:\s*(.*)$")

    i = 0
    while i < len(lines):
        line = lines[i]

        m = metadata_regex.match(line)
        if m:
            # Collect top-level metadata block
            metadata_block = [line]
            j = i + 1
            while j < len(lines):
                if not lines[j].strip():
                    metadata_block.append(lines[j])
                    j += 1
                    continue

                indent = len(lines[j]) - len(lines[j].lstrip())
                if indent == 0:
                    break
                metadata_block.append(lines[j])
                j += 1

            # Find labels in the block
            labels_idx = -1
            labels_indent = 0
            labels_val = ""
            for idx, bline in enumerate(metadata_block):
                lm = labels_regex.match(bline)
                if lm:
                    labels_idx = idx
                    labels_indent = len(lm.group(1))
                    labels_val = lm.group(2).strip()
                    break

            inclusion = '    {{- include "common.labels.standard" . | nindent 4 }}'

            if labels_idx != -1:
                # Check if it has content
                has_content = False
                if labels_val and labels_val not in ("{}", "null"):
                    has_content = True
                else:
                    # Check next non-empty lines in block
                    for k in range(labels_idx + 1, len(metadata_block)):
                        if not metadata_block[k].strip():
                            continue
                        next_indent = len(metadata_block[k]) - len(
                            metadata_block[k].lstrip()
                        )
                        if next_indent > labels_indent:
                            has_content = True
                        break

                if has_content:
                    # Inject under existing labels
                    metadata_block.insert(
                        labels_idx + 1, " " * (labels_indent + 2) + inclusion.strip()
                    )
                else:
                    # Empty or null. "add last in metadata"
                    # Remove the original labels line
                    metadata_block.pop(labels_idx)
                    # Find the last non-empty line to append after
                    last_non_empty = len(metadata_block)
                    for k in range(len(metadata_block) - 1, -1, -1):
                        if metadata_block[k].strip():
                            last_non_empty = k + 1
                            break
                    metadata_block.insert(last_non_empty, "  labels:")
                    metadata_block.insert(last_non_empty + 1, inclusion)
            else:
                # Missing. Add last in metadata.
                last_non_empty = len(metadata_block)
                for k in range(len(metadata_block) - 1, -1, -1):
                    if metadata_block[k].strip():
                        last_non_empty = k + 1
                        break
                metadata_block.insert(last_non_empty, "  labels:")
                metadata_block.insert(last_non_empty + 1, inclusion)

            new_lines.extend(metadata_block)
            i = j
            continue

        new_lines.append(line)
        i += 1

    with open(output_path, "w") as f:
        # Join with original newline style or just \n
        f.write("\n".join(new_lines) + "\n")

    print(f"Converted {input_path} to {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert ISVC template to Helm template"
    )
    parser.add_argument(
        "--from",
        dest="input_source",
        required=True,
        help="Input YAML file or directory",
    )
    parser.add_argument(
        "--to", dest="output_dest", required=True, help="Output file or directory"
    )
    args = parser.parse_args()

    input_source = args.input_source
    output_dest = args.output_dest

    if not os.path.exists(input_source):
        print(f"Error: Source {input_source} not found")
        sys.exit(1)

    if os.path.isdir(input_source):
        # Source is a directory
        if os.path.exists(output_dest) and not os.path.isdir(output_dest):
            print(
                f"Error: Destination {output_dest} must be a directory when source is a directory."
            )
            sys.exit(1)

        if not os.path.exists(output_dest):
            os.makedirs(output_dest, exist_ok=True)

        for filename in os.listdir(input_source):
            if filename.endswith(".yaml"):
                src_file = os.path.join(input_source, filename)

                output_filename = filename.replace(".yaml", ".helm.yaml")
                dst_file = os.path.join(output_dest, output_filename)

                convert_file(src_file, dst_file)

    elif os.path.isfile(input_source):
        # Source is a file
        is_dest_dir = False
        if os.path.isdir(output_dest):
            is_dest_dir = True
        elif output_dest.endswith(os.sep):
            is_dest_dir = True

        if is_dest_dir:
            if not os.path.exists(output_dest):
                os.makedirs(output_dest, exist_ok=True)

            filename = os.path.basename(input_source)
            if filename.endswith(".yaml"):
                out_filename = filename.replace(".yaml", ".helm.yaml")
            else:
                out_filename = filename + ".helm.yaml"

            dst_file = os.path.join(output_dest, out_filename)
        else:
            # Destination is a file path
            dest_dir = os.path.dirname(output_dest)
            if dest_dir and not os.path.exists(dest_dir):
                os.makedirs(dest_dir, exist_ok=True)
            dst_file = output_dest

        convert_file(input_source, dst_file)
    else:
        # Should not happen given exists check
        print(f"Error: Invalid source {input_source}")
        sys.exit(1)


if __name__ == "__main__":
    main()
