{{- $ps := index .Values "prometheus-stack" }}
{{- if and $ps.enabled $ps.grafana.enabled $ps.grafana.sidecar.alerts.enabled .Values.alerts.heimdall.enabled }}
{{- $files := .Files.Glob "files/alerts/*.yaml" }}
{{- if $files }}
{{- range $path, $_ := $files }}
{{- $alertName := base $path | trimSuffix ".yaml" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "common.names.namespace" $ }}
  name: {{ include "common.names.name" $ }}-alert-{{ $alertName }}
  annotations:
    {{- with $ps.grafana.sidecar.alerts.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{ tpl $ps.grafana.sidecar.alerts.label $ }}: {{ ((tpl $ps.grafana.sidecar.alerts.labelValue $) | default 1) | quote }}
    {{- include "mif.labels" $ | nindent 4 }}
data:
  {{ base $path }}: |-
    {{- $.Files.Get $path | replace "__GRAFANA_URL__" ($.Values.alerts.heimdall.grafanaURL | default "") | replace "__RECEIVER__" ($.Values.alerts.heimdall.receiver | default "heimdall-slack") | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
