apiVersion: 1
policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: __RECEIVER__
        object_matchers:
          - - component
            - "="
            - heimdall
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        continue: false
