apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: quickstart-vllm-openai-gpt-oss-20b-prefill-amd-mi300x-tp2
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.preset.labels" . | nindent 4 }}
    mif.moreh.io/model.org: openai
    mif.moreh.io/model.name: gpt-oss-20b
    mif.moreh.io/role: prefill
    mif.moreh.io/accelerator.vendor: amd
    mif.moreh.io/accelerator.model: mi300x
    mif.moreh.io/parallelism: tp2
spec:
  framework: vllm
  model:
    name: openai/gpt-oss-20b
  parallelism:
    tensor: 2
  template:
    spec:
      containers:
        - name: main
          image: 255250787067.dkr.ecr.ap-northeast-2.amazonaws.com/quickstart/moreh-vllm:v0.17.1.1
          env:
            - name: ISVC_EXTRA_ARGS
              value: >-
                --trust-remote-code
                --tool-call-parser openai
                --enable-auto-tool-choice
                --exclude-tools-when-tool-choice-none
                --disable-uvicorn-access-log
                --no-enable-log-requests
                --max-model-len -1
                --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_producer"}'
          resources:
            requests:
              amd.com/gpu: 2
            limits:
              amd.com/gpu: 2
      nodeSelector:
        moai.moreh.io/accelerator.vendor: amd
        moai.moreh.io/accelerator.model: mi300x
      tolerations:
        - key: amd.com/gpu
          operator: Exists
          effect: NoSchedule
